exports.seed = function(knex) {
  return knex('recipes').insert([
    { id: 1 ,
    name: 'Red Curry Noodles',
    dish_id:1,
    ingredients:'human food',
    time:'20 min'},
    { id: 2 ,
      name: 'Buffalo Caesar Wrap',
      dish_id:2,
      ingredients:'human food',
      time:'45 min'},
    { id: 3 ,
      name: 'Sweet Potato Pizza Crust',
      dish_id:3,
      ingredients:'human food',
      time:'40 min'},
    { id: 4 ,
      name: 'Poblano Potato Breakfast Tacos',
      dish_id: 4,
      ingredients:'human food',
      time:'35 min'},
    { id: 5 ,
      name: 'Strawberry Rosé Pancakes',
      dish_id:5,
      ingredients:'human food',
      time:'30 min' },
    { id: 6 ,
      name: 'Skillet Tempeh Pasta ',
      dish_id:6,
      ingredients:'human food',
      time:'45 min'},
  ]);
};
